export enum GcpRoles {
  EDITOR = 'editor',
  IAM_SECURITY_ADMIN = 'iam.securityAdmin',
  PROJECT_IAM_ADMIN = 'resourcemanager.projectIamAdmin',
  SERVICE_ACCOUNT_ADMIN = 'iam.serviceAccountAdmin',
  SERVICE_ACCOUNT_USER = 'iam.serviceAccountUser',
  CERTIFICATE_MANAGER_EDITOR = 'certificatemanager.editor',
  COMPUTE_ADMIN = 'compute.admin',
  COMPUTE_LOAD_BALANCER_ADMIN = 'compute.loadBalancerAdmin',
  COMPUTE_NETWORK_ADMIN = 'compute.networkAdmin',
  CLOUD_SCHEDULER_ADMIN = 'cloudscheduler.admin',
  CLOUD_RUN_ADMIN = 'run.admin',
  CLOUD_RUN_DEVELOPER = 'run.developer',
  CLOUD_RUN_VIEWER = 'run.viewer',
  CLOUDSQL_CLIENT = 'cloudsql.client',
  CLOUDFUNCTIONS_DEVELOPER = 'cloudfunctions.developer',
  STORAGE_OBJECT_ADMIN = 'storage.objectAdmin',
  STORAGE_OBJECT_VIEWER = 'storage.objectViewer',
  BIGQUERY_ADMIN = 'bigquery.admin',
  LOGGING_LOG_WRITER = 'logging.logWriter',
  LOGGING_VIEWER = 'logging.viewer',
  MONITORING_VIEWER = 'monitoring.viewer',
  CLOUDTRACE_AGENT = 'cloudtrace.agent',
  ERROR_REPORTING_USER = 'errorreporting.user',
  ARTIFACT_REGISTRY_READER = 'artifactregistry.reader',
  ARTIFACT_REGISTRY_WRITER = 'artifactregistry.writer',
  CLOUDBUILD_BUILDS_EDITOR = 'cloudbuild.builds.editor',
  BIGQUERY_DATA_VIEWER = 'bigquery.dataViewer',
  BIGQUERY_USER = 'bigquery.user',
}

export enum GcpServices {
  COMPUTE = 'compute',
  RUN = 'run',
  IAM = 'iam',
  SQL_ADMIN = 'sqladmin',
  CERTIFICATE_MANAGER = 'certificatemanager',
  CLOUDRESOURCE_MANAGER = 'cloudresourcemanager',
  CLOUDBUILD = 'cloudbuild',
  CLOUDSCHEDULER = 'cloudscheduler',
  ARTIFACT_REGISTRY = 'artifactregistry',
  CONTAINER = 'container',
  SPEECH = 'speech',
  YOUTUBE = 'youtube',
  DRIVE = 'drive',
}
